# Generated by Django 3.1.5 on 2021-06-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
